# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: torsday

description:
author:
  name: Chris Torstenson
  email: c.torsday@gmail.com
  github: torsday
  twitter: torsday
  # pinterest: asd123
  linkedin: 13298414
  bio: tinkerer & maker
  email_md5: 900152e261a62224334f35b031f38e86

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
